# Generated by Django 5.0.2 on 2024-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_device_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="image",
            field=models.ImageField(null=True, upload_to="upload_models"),
        ),
    ]
