# Generated by Django 5.0.2 on 2024-02-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_alter_device_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload_models"),
        ),
    ]
